### ISSUE TITLE
django-process environment could not be configured

### ISSUE THREAD

**Issue by Cyberfolks** [Jesrat/django-process#2]
im receiving this error can you please guide me how can we get ride on this. thanks in advance.
django-process environment could not be configured due to =>
[Errno 13] Permission denied: '/var/app/venv/staging-LQM1lest/lib/python3.7/site-packages/process/env_conf.json'

**Comment by Jesrat** [comment]
Hi there, this is error is raised when django-process is not able to create the "env_conf.json" file in the package directory, however when this occurs django-process creates the file in the current working directory, this should not be a problem at all. but keep in mind that whe you execute some tasks and perform:

`
import process.env
`

the working dir of the script should be the same where env_conf.json was created.
